### This one should give a "not unique" error
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "+378-900000"
}

### This one should work
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "+4672-4485249"
}

### This one should give a "missing content" error
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jane Doe",
    "number": "+316-39605418"
}

### This one should give a "missing content" error
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jitse van Esch",
    "number": ""
}

### This one should give a wrong phonenumber format error
