### This one should give a "not unique" error
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "+37890"
}

### This one is supposed to work
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jitse van Esch",
    "number": "+31639605418"
}

### This one should give a "missing content" error
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "+31639605418"
}

### This one should give a "missing content" error
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jitse van Esch",
    "number": ""
}
