POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "+37890"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jitse van Esch",
    "number": "+31639605418"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "+31639605418"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jitse van Esch",
    "number": ""
}
