### First add a John Doe
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "+123456789"
}

### Then update John Doe using the Id
PUT http://localhost:3001/api/persons/6595cfa0d354f7d8a99935ce
Content-Type: application/json

{
    "name": "John Doe",
    "number": "+23456789"
}

### Try to update without number
PUT http://localhost:3001/api/persons/6595cfa0d354f7d8a99935ce
Content-Type: application/json

{
    "name": "John Doe",
    "number": ""
}

### Confirm that its updated
GET http://localhost:3001/api/persons
